* NumPy is a wonderful Python package produced by Travis Oliphant, which
has been created fundamentally for scientific computing. It helps handle large
multidimensional arrays and matrices, along with a large library of high-level
mathematical functions to operate on these arrays.
* A NumPy array would require much less memory to store the same amount of data
compared to a Python list, which helps in reading and writing from the array in a
faster manner.

### Creating an array
A list of numbers can be passed to the following array function to create a NumPy
array object:

In [1]:
import numpy as np

In [2]:
n_array = np.array([[0,1,2,3],
                   [4,5,6,7],
                   [8,9,10,11]])

##### A NumPy array object has a number of attributes, which help in giving information about the array. Here are its important attributes:

In [3]:
n_array.ndim

2

* ndim: This gives the number of dimensions of the array. The following shows
that the array that we defined had two dimensions
* n_array has a rank of 2, which is a 2D array.

In [4]:
n_array.shape

(3, 4)

* shape: This gives the size of each dimension of the array:
* The first dimension of n_array has a size of 3 and the second dimension has
a size of 4. This can be also visualized as three rows and four columns.

In [5]:
n_array.size

12

* size: This gives the number of elements
* The total number of elements in n_array is 12.

In [6]:
n_array.dtype

dtype('int32')

* dtype: This gives the datatype of the elements in the array
* The number is stored as 'int32' in n_array

* Mathematical Operations can also be performed on arrays e.g

### Array subtraction
* The following commands subtract the a array from the b array to get the resultant
c array. 

In [7]:
a = np.array( [11, 12, 13, 14])
b = np.array( [ 1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

* The subtraction happens element by element
* Do note that when you subtract or add two arrays, they should be of equal dimensions

### Squaring an array
* The following command raises each element to the power of 2 to obtain this result:

In [8]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

### Conditional operations
* The following command will apply a conditional operation to each of the elements of
the b array, in order to generate the respective Boolean values:

In [9]:
b < 2

array([ True, False, False, False])

### Matrix multiplication
* Two matrices can be multiplied element by element or in a dot product. The
following commands will perform the element-by-element multiplication

In [10]:
A1 = np.array([[1, 1],
                [0, 1]])

A2 = np.array([[2, 0],
                [3, 4]])

A1 * A2

array([[2, 0],
       [0, 4]])

This is similar to multiplying by a scalar, where each element in a particular position of matrix A1 multiplies an element in exactly the same position of matrix A2


#### The dot product can be performed with the following command:

In [11]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

* The result shows that the multiplication follows a Row * Column multiplication, whereby the elements in row1 of matrix A multiplies the elements in column1 of matrix B written in shorthand as (R1C1), the products are summed and placed in the corresponding position of the newly formed matrix. The same process is done for R1C2 and the sum of products is placed in the corresponding position of the newly formed matrix.

* Same thing is done for the next row in Matrix A

* The rule follows that for two martices to be multiplied, they must first be conformable, i.e, The number of columns in the first matrix must be equal to the number of rows in the second matrix. That way the matrices are said to be conformable.

 * Also, the resultant matrix will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.

### Array Slicing
##### selecting a range of values in an array follows the following syntax

In [12]:
n_array[0,0]

0

* The above code pick the element in position 0 for row, and position 0 for columns. Coincidentally, the element in that position is 0

In [13]:
n_array[1,3]

7

The above code selects the element in the position of row 1 and column 3. And the element located in that position is 7

In [14]:
n_array[0:2, 2]

array([2, 6])

* The above code selects the elements located in the range of row 0 to 2 (while excluding the element in the 2nd row) and at column 2. The result therefore is an array with the elements 2 and 6 which are located in row 0 and 1 at column 2

In [15]:
n_array[2, 0:3]

array([ 8,  9, 10])

* The above code selects the elements located in row 2 for the columns in the range 0 to 3 (while excluding the element in the 3 column). The result is an array with the elements 8, 9 and 10 which are located at column 0, 1 and 2 of row 2.

### Importing and working with Pandas

In [24]:
import pandas as pd
pd.Series(np.random.randn(5))

0   -1.123757
1   -0.016469
2    0.235114
3   -1.915646
4    0.184390
dtype: float64

* Above The `random.randn` parameter is part of the NumPy package and it generates random
numbers. 
* The `series` function creates a pandas series that consists of an index, which
is the first column, and the second column consists of random values. At the bottom
of the output is the datatype of the series.


* The index of the series can be customized by calling the following:

In [27]:
pd.Series(np.random.randn(5), index = ['a', 'b', 'c', 'd', 'e'])

a   -1.562585
b   -1.307292
c    0.505566
d   -1.371162
e    0.024265
dtype: float64

**A series can be generated from a python dictionary using the following:**

In [29]:
dic = {'a':10, 'b':20, 'c':30, 'd':40}

pd.Series(dic)

a    10
b    20
c    30
d    40
dtype: int64

In [56]:
d = {'Item1': pd.DataFrame(np.random.randn(4, 3)),
'Item2': pd.DataFrame(np.random.randn(4, 2))}
d

{'Item1':           0         1         2
 0 -0.073742 -0.732915 -1.126560
 1 -0.426625  1.218264 -0.117098
 2 -2.961812 -0.115702 -0.871880
 3  1.168921 -1.323624  0.369280, 'Item2':           0         1
 0 -1.569878 -1.612503
 1  0.239432 -2.885602
 2  0.220342 -0.570147
 3 -1.303881 -0.969353}

In [72]:
excel = pd.read_excel("JOE'S DATA.xlsx", encoding = 'utf8')

excel

,YEAR,GDP,INV (EDUINF),INV (HCD),POLSTA,INV (VOC EDU),L_GDP,L_INV (EDUINF)
0,1985,192.273267,5.003672,2.360465,0.459600,1.154000,2.283919,0.699289
1,1986,202.440000,5.249008,2.476202,0.264800,0.655400,2.306296,0.720077
2,1987,249.440000,5.486108,2.588053,1.816200,0.619100,2.396966,0.739264
3,1988,320.330000,6.729796,3.174759,1.898600,1.726000,2.505598,0.828002
4,1989,419.200000,7.493046,3.534819,2.617500,1.844800,2.622421,0.874658
5,1990,499.680000,8.288179,3.909921,2.919900,2.096000,2.698692,0.918459
6,1991,596.040000,9.893773,4.667354,3.345000,1.491700,2.775275,0.995362
7,1992,909.800000,25.477112,12.018742,5.118500,2.132600,2.958946,1.406150
8,1993,1259.070000,37.091825,17.497944,8.081700,3.575300,3.100050,1.569278
9,1994,1762.812817,42.970103,20.271001,8.785100,4.994400,3.246206,1.633166


In [89]:
excel[0:5]['YEAR']

0    1985
1    1986
2    1987
3    1988
4    1989
Name: YEAR, dtype: int64